### ISSUE TITLE
If still exists - some questions are not make sense (rivers, roads, landuse=residential)

### ISSUE THREAD

**Issue by pawlosck** [Helium314/SCEE#521]
SCEE ask me if things like rivers, roads, "landuse=residential" still exists. It's not make sense.

**Does it happen in normal StreetComplete?**
I don't know. I don't have SC installed.

**Versions affected**
Android: 14
SCEE: 57.0 (f-droid)

**Comment by Helium314** [comment]
already fixed in https://github.com/Helium314/SCEE/commit/7dee11fe28939615a0db32fdd5fb800475edbca4

**Comment by matkoniecz** [comment]
@Helium314 If you have a bit of time... Can you explain why https://github.com/Helium314/SCEE/commit/7dee11fe28939615a0db32fdd5fb800475edbca4 was needed?

I have the same bug in my fork and even with this commit I still do not understand why it happens to me while not happening in normal StreetComplete

**Comment by Helium314** [comment]
It's part of changing the "is shop expression" to `.isPlace()`, where the shop expression filter was removed from the element filter and replaced by `isPlace` in `isApplicableTo`.
I had removed the `isApplicableTo` part previously, and the upstream change of the element filter didn't trigger any merge conflict, so I didn't notice that now an important part of tag filtering is actually done by `.isPlace()`.

**Comment by mnalis** [comment]
For those experiencing this bug, it seems that just upgrading to [SCEE v57.2](https://github.com/Helium314/SCEE/releases/tag/v57.2)  is not enough; one also needs to do `Settings` / `Delete cache`.

**Comment by Helium314** [comment]
Or alternatively use the dynamic quest creation setting. Or re-download, which auto-download does by itself after an upgrade (you can of course do it manually too).

**Comment by mnalis** [comment]
> Or re-download, which auto-download does by itself after an upgrade (you can of course do it manually too).

Interestingly, I do have auto-download enabled, but after upgrade SCEE still showed _"Is this stream still here?"_ type of quests, even after few minutes. 

I'm not sure if I'm interpreting your comment above correctly, but it seems to say it shouldn't have happened (i.e. the SCEE should've automatically re-downloaded the quests in the visible area when I started it after the upgrade?)

**Comment by Helium314** [comment]
Yes, it should re-download. But maybe it doesn't clean old quests when doing that, not sure

**Comment by matkoniecz** [comment]
AFAIK it should be
